### ISSUE TITLE
[155][157] 交叉编译下RVPath变量在指定汇编器和链接器时无效

### ISSUE THREAD

**Issue by iwzbi** [sunshaoce/rvcc#5]
https://github.com/sunshaoce/rvcc/blob/40c240d9eb629b44f175c35ad1a87935fa63bcf3/main.c#L252

https://github.com/sunshaoce/rvcc/blob/40c240d9eb629b44f175c35ad1a87935fa63bcf3/main.c#L321

请参考https://github.com/sunshaoce/rvcc/blob/40c240d9eb629b44f175c35ad1a87935fa63bcf3/main.c#L331-L334
合并字符串

**Comment by sunshaoce** [comment]
已经修复，非常感谢！
