### ISSUE TITLE
关于stage2的问题

### ISSUE THREAD

**Issue by qian160** [sunshaoce/rvcc#7]
stage2/rvcc 是riscv版本的，于是只能在qemu上运行，但是运行起来后会有奇怪的报错信息，例如：
> stage2/rvcc: 1: ELF��@�8: not found
stage2/rvcc: 3: Syntax error: "(" unexpected

猜测可能是fork-exec模型的问题。执行execvp函数后把qemu也覆盖掉了，然后尝试直接在x86环境下运行riscv版本的rvcc导致的错误。如果不去执行fork-exec，例如只是用--help打印信息就能正常在qemu里运行stage2/rvcc并退出。

**Comment by sunshaoce** [comment]
嗯，所以还是推荐在RISC-V环境下，进行实验。

**Comment by qian160** [comment]
明白了，感谢大佬回复😃
