### ISSUE TITLE
这个风格的汇编在arm架构的mac电脑比如m3芯片能直接运行吗

### ISSUE THREAD

**Issue by maolovecoding** [sunshaoce/rvcc#8]

**Comment by sunshaoce** [comment]
不可以。mac m系列使用的是arm指令集，这个是riscv指令集。
________________________________
发件人: maojun ***@***.***>
发送时间: Friday, January 12, 2024 1:22:56 PM
收件人: sunshaoce/rvcc ***@***.***>
抄送: Subscribed ***@***.***>
主题: [sunshaoce/rvcc] 这个风格的汇编在arm架构的mac电脑比如m3芯片能直接运行吗 (Issue #8)


―
